### ISSUE TITLE
Support for deletion

### ISSUE THREAD

**Issue by nab-gha** [paulcarlton-ww/k8s-dr-utils#2]
There needs to be a delete key from bucket method to support deletion of object on source cluster.
The create_key_yaml method will need to be split into create key and  process the data so deletion can build the key without having any data to process.
Add changes to support backup iterating through the key in S3 and removing any that don't exist in the  cluster.
The updater called by the AdmissionController will need to delete keys it gets deletion notifications for

**Comment by richardcase** [comment]
I'll start adding this

**Comment by richardcase** [comment]
Complete
